version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export BASE_URL="$BASE_URL"' >> $BASH_ENV
            echo 'export API_BASE_URL="$API_BASE_URL"' >> $BASH_ENV
            echo 'export MODE="$MODE"' >> $BASH_ENV
            echo 'export SENTRY_DSN="$SENTRY_DSN"' >> $BASH_ENV
            echo 'export GA_TRACKING_ID="$GA_TRACKING_ID"' >> $BASH_ENV
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
      - run:
          name: Dependencies
          command: make node_modules
      - save_cache:
          paths:
          - ./node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: make lint
      - run:
          name: Build
          command: make build
      - run:
          name: Push images
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker login $DOCKER_REGISTRY_HOST -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS
              make push
            fi
      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
               make deploy
            fi
