version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export BASE_URL="$BASE_URL"' >> $BASH_ENV
            echo 'export API_BASE_URL="$API_BASE_URL"' >> $BASH_ENV
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
      - run:
          name: Dependencies
          command: make node_modules
      - save_cache:
          paths:
          - ./node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: make lint
      - run:
          name: Build
          command: cp -R ~/.ssh ./ssh && make build
      - run:
          name: Push images
          command: |
            docker login $DOCKER_REGISTRY_HOST -u $DOCKER_REGISTRY_LOGIN -p $DOCKER_REGISTRY_PASSWORD
            make push
      - run:
          name: Deploy
          command: make deploy
