version: '2'

services:
  node:
    build:
      context: ./..
      dockerfile: ./.docker/node/Dockerfile
    volumes:
      - ../dist:/code/dist
    restart: unless-stopped
    ports:
      - "80:3000"
