version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/geenzever-website-nginx
    environment:
      - VIRTUAL_HOST=geenzever.be
      - LETSENCRYPT_HOST=geenzever.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    restart: unless-stopped
    networks:
      - default
      - webproxy
    mem_limit: 8m

  node:
    image: docker.wouterdeschuyter.be/geenzever-website-node
    mem_limit: 64m
    networks:
      - default
      - database

networks:
  webproxy:
    external: true
  database:
    external: true
