version: '2'

services:
  mariadb:
    image: mariadb:10.3
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:5-alpine
    volumes:
      - ./data/redis/:/data
    ports:
      - "6379:6379"

  node:
    image: node:10-slim
    command: ["./node_modules/.bin/ts-node", "-r", "./src/bootstrap", "./src/server"]
    volumes:
      - ./../:/code
    environment:
      - DATABASE_HOST=mariadb
      - PORT=3001
    working_dir: /code
    restart: unless-stopped
    ports:
      - "3001:3001"
