version: '2'

services:
  mariadb:
    image: mariadb:10.3
    volumes:
      - ./data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  node:
    build:
      context: ./..
      dockerfile: ./.docker/node/Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
